// Code generated by go-swagger; DO NOT EDIT.

package screenshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Webseite-Herunterladen-de/screenshot-capture-api-go/models"
)

// CaptureScreenshotUnauthenticatedReader is a Reader for the CaptureScreenshotUnauthenticated structure.
type CaptureScreenshotUnauthenticatedReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *CaptureScreenshotUnauthenticatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCaptureScreenshotUnauthenticatedOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 302:
		result := NewCaptureScreenshotUnauthenticatedFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewCaptureScreenshotUnauthenticatedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCaptureScreenshotUnauthenticatedOK creates a CaptureScreenshotUnauthenticatedOK with default headers values
func NewCaptureScreenshotUnauthenticatedOK(writer io.Writer) *CaptureScreenshotUnauthenticatedOK {
	return &CaptureScreenshotUnauthenticatedOK{

		Payload: writer,
	}
}

/* CaptureScreenshotUnauthenticatedOK describes a response with status code 200, with default header values.

the requested screenshot as binary
*/
type CaptureScreenshotUnauthenticatedOK struct {
	ContentType            string
	Location               string
	XREMAININGQUOTA        int64
	XREMAININGQUOTAPREPAID int64

	Payload io.Writer
}

func (o *CaptureScreenshotUnauthenticatedOK) Error() string {
	return fmt.Sprintf("[GET /capture/{token}][%d] captureScreenshotUnauthenticatedOK  %+v", 200, o.Payload)
}
func (o *CaptureScreenshotUnauthenticatedOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *CaptureScreenshotUnauthenticatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Type
	hdrContentType := response.GetHeader("Content-Type")

	if hdrContentType != "" {
		o.ContentType = hdrContentType
	}

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	// hydrates response header X-REMAINING-QUOTA
	hdrXREMAININGQUOTA := response.GetHeader("X-REMAINING-QUOTA")

	if hdrXREMAININGQUOTA != "" {
		valxREMAININGQUOTA, err := swag.ConvertInt64(hdrXREMAININGQUOTA)
		if err != nil {
			return errors.InvalidType("X-REMAINING-QUOTA", "header", "int64", hdrXREMAININGQUOTA)
		}
		o.XREMAININGQUOTA = valxREMAININGQUOTA
	}

	// hydrates response header X-REMAINING-QUOTA-PREPAID
	hdrXREMAININGQUOTAPREPAID := response.GetHeader("X-REMAINING-QUOTA-PREPAID")

	if hdrXREMAININGQUOTAPREPAID != "" {
		valxREMAININGQUOTAPREPAId, err := swag.ConvertInt64(hdrXREMAININGQUOTAPREPAID)
		if err != nil {
			return errors.InvalidType("X-REMAINING-QUOTA-PREPAID", "header", "int64", hdrXREMAININGQUOTAPREPAID)
		}
		o.XREMAININGQUOTAPREPAID = valxREMAININGQUOTAPREPAId
	}

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCaptureScreenshotUnauthenticatedFound creates a CaptureScreenshotUnauthenticatedFound with default headers values
func NewCaptureScreenshotUnauthenticatedFound() *CaptureScreenshotUnauthenticatedFound {
	return &CaptureScreenshotUnauthenticatedFound{}
}

/* CaptureScreenshotUnauthenticatedFound describes a response with status code 302, with default header values.

the requested screenshot as redirect
*/
type CaptureScreenshotUnauthenticatedFound struct {
	Location               string
	XREMAININGQUOTA        int64
	XREMAININGQUOTAPREPAID int64
}

func (o *CaptureScreenshotUnauthenticatedFound) Error() string {
	return fmt.Sprintf("[GET /capture/{token}][%d] captureScreenshotUnauthenticatedFound ", 302)
}

func (o *CaptureScreenshotUnauthenticatedFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	// hydrates response header X-REMAINING-QUOTA
	hdrXREMAININGQUOTA := response.GetHeader("X-REMAINING-QUOTA")

	if hdrXREMAININGQUOTA != "" {
		valxREMAININGQUOTA, err := swag.ConvertInt64(hdrXREMAININGQUOTA)
		if err != nil {
			return errors.InvalidType("X-REMAINING-QUOTA", "header", "int64", hdrXREMAININGQUOTA)
		}
		o.XREMAININGQUOTA = valxREMAININGQUOTA
	}

	// hydrates response header X-REMAINING-QUOTA-PREPAID
	hdrXREMAININGQUOTAPREPAID := response.GetHeader("X-REMAINING-QUOTA-PREPAID")

	if hdrXREMAININGQUOTAPREPAID != "" {
		valxREMAININGQUOTAPREPAId, err := swag.ConvertInt64(hdrXREMAININGQUOTAPREPAID)
		if err != nil {
			return errors.InvalidType("X-REMAINING-QUOTA-PREPAID", "header", "int64", hdrXREMAININGQUOTAPREPAID)
		}
		o.XREMAININGQUOTAPREPAID = valxREMAININGQUOTAPREPAId
	}

	return nil
}

// NewCaptureScreenshotUnauthenticatedDefault creates a CaptureScreenshotUnauthenticatedDefault with default headers values
func NewCaptureScreenshotUnauthenticatedDefault(code int) *CaptureScreenshotUnauthenticatedDefault {
	return &CaptureScreenshotUnauthenticatedDefault{
		_statusCode: code,
	}
}

/* CaptureScreenshotUnauthenticatedDefault describes a response with status code -1, with default header values.

unexpected error
*/
type CaptureScreenshotUnauthenticatedDefault struct {
	_statusCode int
	ContentType string

	Payload *models.ErrorModel
}

// Code gets the status code for the capture screenshot unauthenticated default response
func (o *CaptureScreenshotUnauthenticatedDefault) Code() int {
	return o._statusCode
}

func (o *CaptureScreenshotUnauthenticatedDefault) Error() string {
	return fmt.Sprintf("[GET /capture/{token}][%d] captureScreenshotUnauthenticated default  %+v", o._statusCode, o.Payload)
}
func (o *CaptureScreenshotUnauthenticatedDefault) GetPayload() *models.ErrorModel {
	return o.Payload
}

func (o *CaptureScreenshotUnauthenticatedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Type
	hdrContentType := response.GetHeader("Content-Type")

	if hdrContentType != "" {
		o.ContentType = hdrContentType
	}

	o.Payload = new(models.ErrorModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
